# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: teal

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: "Chi's personal website."
    twitter: 'codescv'
  analytics:
    google_analytics: 'G-MNC5N5WMNY'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    show_search: true
    show_theme_chooser: true


# Site footer
footer:
  copyright:
    notice: '© {year} Chi. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  syntax_highlighter:
    theme_light: xcode-light
    theme_dark: xcode-dark
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/codescv/codescv.github.io'
    content_dir: content
    branch: main
  comment:
    # Choose a provider: giscus, disqus, commento, or '' to disable commenting
    provider: 'giscus'
    giscus:
      repo: 'codescv/codescv.github.io'
      repo_id: 'R_kgDOK2Vn_A'
      category: 'General'
      category_id: 'DIC_kwDOK2Vn_M4Cbp8J'
      theme: preferred_color_scheme
      language_code: en
      mapping: pathname

